version: '3.6'
services:
  # mqtt_broker:
  #   image: eclipse-mosquitto:1.6.15
  #   container_name: mqtt_broker
  #   restart: always
  #   ports:
  #     - 1883:1883
  #     - 9001:9001
  #   volumes:
  #     - ./mqtt/config:/mosquitto/config
  #     - persistant_data:/mosquitto/data
  #     - ./mqtt/mosquitto.log:/mosquitto/log/mosquitto.log
  backend:
    image: dreammnck/wireless-project:1.0.0
    container_name: backend
    depends_on:
      - mqtt_broker
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
volumes: 
  persistant_data:
